### ISSUE TITLE
reset-sim not working on Xcode 7 and OS 10.11

### ISSUE THREAD

**Issue by GantMan** [OTGApps/reset-sim#2]
Error you get is "Can't get application "iOS Simulator"

**Comment by markrickert** [comment]
So it looks like they may have changed the name of "iOS Simulator" in Xcode 7. Can you let me know what it says in the dock when you hover over the simulator application?

**Comment by GantMan** [comment]
"Simulator"

**Comment by markrickert** [comment]
For serious? Is that what it says in the top menu bar next to the Apple logo while the app is open?

**Comment by GantMan** [comment]
yup!
![image](https://cloud.githubusercontent.com/assets/997157/9529528/714bc96c-4cc0-11e5-93ea-c29bf9d3cd81.png)

**Comment by markrickert** [comment]
Can you try this branch? https://github.com/OTGApps/reset-sim/tree/xcode7_fix

**Comment by scally** [comment]
I can confirm this branch worked for me v10.11.1, XCode 7.0 7A220.
Still outputs an error, but then the simulator reset happens:

```
35:54: execution error: Can’t get application "iOS Simulator". (-1728)
button Reset of window 1 of application process Simulator
```

**Comment by scally** [comment]
I created a PR with an attempt at figuring out which name to use for Simulator before issuing the reset commands. I can imagine it might still have an issue if the Simulator isn't open yet, so maybe there's a better way of figuring out which to use. 

https://github.com/OTGApps/reset-sim/pull/3
